#!/usr/bin/env python
import sys, argparse
from os import environ
import oursql as mysql
from icinga2_notification_limit.config import ConfigReader
from icinga2_notification_limit.limit import LimitChecker

# Parse arguments
parser = argparse.ArgumentParser( description='mail-notification-script for icinga2 with limits configurable per sender')
parser.add_argument('-r','--recipient', help='Recipient of the notification',required=True)
parser.add_argument('-c','--config', help='Path to the icinga2 ido-mysql config file (Default: '+ConfigReader.DEFAULT_CONFIG_FILE+')',required=False)
args = parser.parse_args()

recipient = args.recipient

# Get Configuration
config = ConfigReader(args.config).getConfig()
limitsTable = config['table_prefix']+'mailnotification_limits'
countersTable = config['table_prefix']+'mailnotification_counters'

# Connect to DB
try:
    db = mysql.connect(host=config['host'], user=config['user'], \
        passwd=config['password'], db=config['database']);
except mysql.Error as exception:
    print "Error %d: %s" % (exception.args[0], exception.args[1])
    sys.exit(-1)

# Get Cursor
try:
    cur = db.cursor()
except mysql.Error as exception:
    if db:
        db.close()
    print "Error %d: %s" % (exception.args[0], exception.args[1])
    sys.exit(-1)

# Do the magic
try:
    # Use transaction for isolation
    cur.execute('START TRANSACTION')
    # Get current values
    cur.execute('SELECT updated, timerange, counter, maximum FROM ' + countersTable + \
        ' as c JOIN ' + limitsTable + ' as l ON l.id = c.limitId' + \
        ' WHERE recipient = ? FOR UPDATE', (recipient,))
    row = cur.fetchone()

    # if any limit configured for recipient
    if row:
        # Check if limit reached
        newValue = LimitChecker.Check(counter=row[2], maximum=row[3], \
            updated=row[0], timerange=row[1])
        # Update counter
        if newValue:
            cur.execute('UPDATE ' + countersTable + ' SET counter = ?' + \
                ', updated = CURRENT_TIMESTAMP' + \
                ' WHERE recipient = ?', (newValue, recipient))
            exitCode = 0
        else:
            print 'reached limit for recipient ' + recipient + '. not sending email'
            exitCode = 1
    else:
        print 'recipient ' + recipient + ' not found in database'
        exitCode = 0

    db.commit()
except mysql.Error as exception:
    if db:
        db.rollback()
    print "Error %d: %s" % (exception.args[0], exception.args[1])
    sys.exit(-1)
finally:
    if cur:
        cur.close()
    if db:
        db.close()

sys.exit(exitCode)
