#!/usr/bin/env python
from icinga2_mail_notification_limit.config import ConfigReader
import sys
import datetime
from os import environ
import oursql as mysql

recipient = environ.get("USEREMAIL")
config = ConfigReader('/home/fabian.jucker/06_dev/icinga2_mail_notification_limit/testconfig').getConfig()
limitsTable = config['table_prefix']+'mailnotification_limits'
countersTable = config['table_prefix']+'mailnotification_counters'

# TODO: refactor
try:
    db = mysql.connect(host=config['host'], user=config['user'], \
        passwd=config['password'], db=config['database']);

    cur = db.cursor()
    cur.execute('START TRANSACTION')
    cur.execute('SELECT updated, timerange, counter, maximum FROM ' + countersTable + \
        ' as c JOIN ' + limitsTable + ' as l ON l.id = c.limitId' + \
        ' WHERE recipient = ? FOR UPDATE', (recipient,))

    row = cur.fetchone()

    updated = row[0]
    timerange = row[1]
    counter = row[2]
    maximum = row[3]

    if (updated + datetime.timedelta(0, timerange)) < datetime.datetime.utcnow():
        cur.execute('UPDATE ' + countersTable + ' SET counter = 1,' + \
            ' updated = CURRENT_TIMESTAMP' + \
            ' WHERE recipient = ?', (recipient,))
        # TODO: send mail
    elif counter < maximum:
        cur.execute('UPDATE ' + countersTable + ' SET counter = ?' + \
            ', updated = CURRENT_TIMESTAMP' + \
            ' WHERE recipient = ?', (counter + 1, recipient))
        # TODO: send mail
    else:
        # TODO: log warning / do nothing
        print ""

    db.commit()
except mysql.Error as exception:
    print "Error %d: %s" % (exception.args[0], exception.args[1])
    sys.exit(1)
finally:
    if cur:
        cur.close()
    if db:
        db.rollback()
        db.close()
