#!/usr/bin/env python
from icinga2_mail_notification_limit.config import ConfigReader
import sys
import datetime
from os import environ
import MySQLdb as mysql

recipient = environ.get("USEREMAIL")
config = ConfigReader('/home/fabian.jucker/06_dev/icinga2_mail_notification_limit/testconfig').getConfig()
limitsTable = config['table_prefix']+'mailnotification_limits'
countersTable = config['table_prefix']+'mailnotification_counters'

try:
    db = mysql.connect(config['host'], config['user'], config['password'], config['database']);

    cur = db.cursor()
    cur.execute('START TRANSACTION')
    cur.execute('SELECT updated, timerange, counter, maximum FROM ' + countersTable + \
        ' as c JOIN ' + limitsTable + ' as l ON l.id = c.limitId' + \
        ' WHERE recipient = \'' + recipient + '\' FOR UPDATE')

    row = cur.fetchone()

    updated = row[0]
    timerange = row[1]
    counter = row[2]
    maximum = row[3]

    if (updated + datetime.timedelta(0, timerange)) < datetime.datetime.utcnow():
        cur.execute('UPDATE ' + countersTable + ' SET counter = 1,' + \
            ' updated = CURRENT_TIMESTAMP' + \
            ' WHERE recipient = \'' + recipient + '\'')
        // TODO: send mail
    elif counter < maximum:
        cur.execute('UPDATE ' + countersTable + ' SET counter = ' + \
            str(counter + 1) + ', updated = CURRENT_TIMESTAMP' + \
            ' WHERE recipient = \'' + recipient + '\'')
        // TODO: send mail
    else:
        // TODO: log warning / do nothing

    db.commit()
except mysql.Error as exception:
    print "Error %d: %s" % (exception.args[0], exception.args[1])
    sys.exit(1)
finally:
    if cur:
        cur.close()
    if db:
        db.rollback()
        db.close()
